#we use java
language: java

#we add the java development kit (jdk)
jdk:
  - oraclejdk13
# SonarCloud
addons:
  sonarcloud:
    organization: "nielshendrickx"
    token:
      secure: "vc5D+LtSub2i95CGEdniobzzX6LkoLypETMTU0IjPM5VA1JvHpGLdHcLqDjcM6bUDWOo67EXsNddYQoqPeGQijluJ75eS7VVFHnmhBgac7pajTo+KR0CnDYqtWX/zvItupzYtjWP+au1B9IcCuwSaoAGYI7s/tziunbNYOTWRLtu6bym9okTi9Vpw6HeNFf9CPraHG0s8HqMo0eu+tvia2SSwZPYe8pKJFupYVvRcJ08FwdFojrB3b2LCMzT6lnnfS9VzmtmHr7PS5SHnL7p66/k6NIPkmd4h8bwkmS+nhNnNwXDTFWRsuy42bi1YoiDPWfN/DbDjfV7vW/3vHrlRkRQPaIe/G65jJ5olL1tIX+HOtBGN23JA+wMwXdpUxRgXg6mTC+VM0PcBJqhNI3RT5ifH/YQI5HyyE7yJUTIRfXkGcliRlLHr/GSdeat8mRz2OLiaT5ojmQzx0HtzWVw87o8rYGHgpX7S8FtELclXSBM8O+4NBbgOEy0LWA8CimPjKr4vykXGwR5ItfKHA744A/YrpYbZlk89XtrU9YlVxXVyKnMGo40ghtgH4mvvgXilmUZPpHqv+R/P2Hpg/8z3ZT2LS/JstDUdM0c6L5c44Tl101PQ67bYnZghRP6srvVxRma/UD8oVBYgRkF6c8d0GfQAlQCUBcuJvJy2qbuCBY="

before_install:
  - mvn clean

script:
  #We avoid this error :" the job exceeded the maximum log length and has been terminated "
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <mirrors>\n    <mirror>\n      <id>mvnsearch-unavailable</id>\n      <name>mvnsearch-unavailable</name>\n      <mirrorOf>mvnsearch</mirrorOf>\n      <url>http://repo1.maven.org/maven2</url>\n    </mirror>\n  </mirrors>\n  <profiles>\n    <profile>\n      <id>no-mvnsearch</id>\n      <repositories>\n        <repository>\n          <id>mvnsearch</id>\n          <url>http://www.mvnsearch.org/maven2</url>\n          <releases>\n            <enabled>true</enabled>\n          </releases>\n          <snapshots>\n            <enabled>true</enabled>\n          </snapshots>\n        </repository>\n      </repositories>\n    </profile>\n  </profiles>\n  <activeProfiles>\n    <activeProfile>no-mvnsearch</activeProfile>\n  </activeProfiles>\n</settings>' > $HOME/.m2/settings.xml
  - cat $HOME/.m2/settings.xml
  # SonarCloud
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Pcoverage -Dsonar.projectKey=nielshendrickx_Order_backend
  # codecoverage
  - bash <(curl -s https://codecov.io/bash)

after_success:
  #deploying the app on Heroku
  - cd jar
  - mvn heroku:deploy